"""add lead collection import jobs

Revision ID: 21a40470e494
Revises: 3f2dfbe6340d
Create Date: 2026-08-03 16:50:47.095567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a40470e494'
down_revision: Union[str, None] = '3f2dfbe6340d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='import_job_status'), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('retry_of_job_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retry_of_job_id'], ['import_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_created_by'), 'import_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_import_jobs_provider'), 'import_jobs', ['provider'], unique=False)
    op.create_index('ix_import_jobs_provider_created', 'import_jobs', ['provider', 'created_at'], unique=False)
    op.create_index(op.f('ix_import_jobs_retry_of_job_id'), 'import_jobs', ['retry_of_job_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_started_at'), 'import_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_index('ix_import_jobs_status_created', 'import_jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_jobs_status_created', table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_started_at'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_retry_of_job_id'), table_name='import_jobs')
    op.drop_index('ix_import_jobs_provider_created', table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_provider'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_created_by'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # Alembic's autogenerated downgrade drops the table but not the ENUM type the upgrade
    # implicitly created, which leaves `import_job_status` behind and makes a subsequent
    # re-upgrade fail with "type already exists". Dropped explicitly here.
    sa.Enum(name='import_job_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
