"""add whatsapp campaign management

Revision ID: 3f2dfbe6340d
Revises: 504f5c5d4a31
Create Date: 2026-08-03 16:00:37.722910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f2dfbe6340d'
down_revision: Union[str, None] = '504f5c5d4a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('MARKETING', 'UTILITY', 'AUTHENTICATION', 'SERVICE', name='whatsapp_template_category'), server_default='MARKETING', nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_category'), 'whatsapp_templates', ['category'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_id'), 'whatsapp_templates', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_is_active'), 'whatsapp_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_name'), 'whatsapp_templates', ['name'], unique=False)
    op.create_index('uq_whatsapp_templates_name_active', 'whatsapp_templates', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('whatsapp_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'CANCELLED', name='whatsapp_campaign_status'), server_default='DRAFT', nullable=False),
    sa.Column('total_recipients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_delivered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_replied', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_campaigns_created_by'), 'whatsapp_campaigns', ['created_by'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaigns_id'), 'whatsapp_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaigns_name'), 'whatsapp_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaigns_scheduled_at'), 'whatsapp_campaigns', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaigns_status'), 'whatsapp_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaigns_template_id'), 'whatsapp_campaigns', ['template_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('message_status', sa.Enum('PENDING', 'QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'REPLIED', name='campaign_message_status'), server_default='PENDING', nullable=False),
    sa.Column('rendered_message', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['whatsapp_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'lead_id', name='uq_campaign_recipients_campaign_lead')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_recipients_campaign_status', 'campaign_recipients', ['campaign_id', 'message_status'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_id'), 'campaign_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_lead_id'), 'campaign_recipients', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_message_status'), 'campaign_recipients', ['message_status'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_phone'), 'campaign_recipients', ['phone'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_provider_message_id'), 'campaign_recipients', ['provider_message_id'], unique=False)
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_leads_last_contacted_at'), 'leads', ['last_contacted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_last_contacted_at'), table_name='leads')
    op.drop_column('leads', 'last_contacted_at')
    op.drop_index(op.f('ix_campaign_recipients_provider_message_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_phone'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_message_status'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_lead_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_id'), table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_campaign_status', table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_whatsapp_campaigns_template_id'), table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_status'), table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_scheduled_at'), table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_name'), table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_id'), table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_created_by'), table_name='whatsapp_campaigns')
    op.drop_table('whatsapp_campaigns')
    op.drop_index('uq_whatsapp_templates_name_active', table_name='whatsapp_templates', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_whatsapp_templates_name'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_is_active'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_category'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    # Autogenerate does not emit these. Postgres keeps an ENUM type after the only table
    # using it is dropped, so without an explicit DROP TYPE a downgrade followed by a
    # re-upgrade fails with "type '...' already exists". Same fix as the lead_activities
    # migration (504f5c5d4a31).
    sa.Enum(name='campaign_message_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='whatsapp_campaign_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='whatsapp_template_category').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
