"""add lead activities and notes

Revision ID: 504f5c5d4a31
Revises: 2dcb418e93d7
Create Date: 2026-08-03 15:00:10.350686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504f5c5d4a31'
down_revision: Union[str, None] = '2dcb418e93d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('CREATED', 'UPDATED', 'WHATSAPP_SENT', 'WHATSAPP_DELIVERED', 'WHATSAPP_READ', 'WHATSAPP_REPLIED', 'PHONE_CALL', 'FOLLOW_UP', 'NOTE', 'STATUS_CHANGED', 'CONVERTED', 'DELETED', name='lead_activity_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_activity_type'), 'lead_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_lead_activities_created_at'), 'lead_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_activities_created_by_employee_id'), 'lead_activities', ['created_by_employee_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index('ix_lead_activities_lead_id_created_at', 'lead_activities', ['lead_id', sa.text('created_at DESC')], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_created_by_employee_id'), 'lead_notes', ['created_by_employee_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_created_by_employee_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index('ix_lead_activities_lead_id_created_at', table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_created_by_employee_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_created_at'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_activity_type'), table_name='lead_activities')
    op.drop_table('lead_activities')
    # Autogenerate does not emit this. Postgres keeps an ENUM type after the only table
    # using it is dropped, so without an explicit DROP TYPE a downgrade followed by a
    # re-upgrade fails with "type 'lead_activity_type' already exists".
    sa.Enum(name='lead_activity_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
