"""add lead youtube column

Revision ID: 5fa580580353
Revises: a1f4c7b93e02
Create Date: 2026-08-08 11:39:13.501977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa580580353'
down_revision: Union[str, None] = 'a1f4c7b93e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('youtube', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'youtube')
    # ### end Alembic commands ###
