"""add_production_hardening_constraints

Revision ID: 730044ddb4c2
Revises: 72fe5e578528
Create Date: 2026-08-02 12:05:00.857015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730044ddb4c2'
down_revision: Union[str, None] = '72fe5e578528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_active_invoice_per_order', 'invoices', ['order_id'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    op.drop_constraint('notification_logs_order_id_fkey', 'notification_logs', type_='foreignkey')
    op.create_foreign_key(None, 'notification_logs', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Add CHECK constraints manually
    op.create_check_constraint("chk_payment_amount_positive", "payments", "amount > 0")
    op.create_check_constraint("chk_invoice_discount_non_negative", "invoices", "discount >= 0")
    op.create_check_constraint("chk_invoice_gst_percentage_valid", "invoices", "gst_percentage >= 0 AND gst_percentage <= 100")
    op.create_check_constraint("chk_invoice_grand_total_non_negative", "invoices", "grand_total >= 0")
    op.create_check_constraint("chk_invoice_paid_amount_non_negative", "invoices", "paid_amount >= 0")
    op.create_check_constraint("chk_delivery_dates_logical", "deliveries", "dispatch_date IS NULL OR delivered_date IS NULL OR dispatch_date <= delivered_date")


def downgrade() -> None:
    # Drop CHECK constraints manually
    op.drop_constraint("chk_delivery_dates_logical", "deliveries", type_="check")
    op.drop_constraint("chk_invoice_paid_amount_non_negative", "invoices", type_="check")
    op.drop_constraint("chk_invoice_grand_total_non_negative", "invoices", type_="check")
    op.drop_constraint("chk_invoice_gst_percentage_valid", "invoices", type_="check")
    op.drop_constraint("chk_invoice_discount_non_negative", "invoices", type_="check")
    op.drop_constraint("chk_payment_amount_positive", "payments", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_logs', type_='foreignkey')
    op.create_foreign_key('notification_logs_order_id_fkey', 'notification_logs', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_active_invoice_per_order', table_name='invoices', postgresql_where=sa.text("status != 'CANCELLED'"))
    # ### end Alembic commands ###
