"""add_crm_lead_fields

Revision ID: 8709649b25f0
Revises: 8bd6d5a9f5a6
Create Date: 2026-08-02 10:03:35.949436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.photographer import LeadStatus, LeadPriority, ContactMethod

# revision identifiers, used by Alembic.
revision: str = '8709649b25f0'
down_revision: Union[str, None] = '8bd6d5a9f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create custom enum types in PostgreSQL first
    # Using postgresql.ENUM with op.get_bind() to execute the CREATE TYPE statements
    lead_status_enum = postgresql.ENUM(LeadStatus, name='leadstatus')
    lead_status_enum.create(op.get_bind(), checkfirst=True)
    
    lead_priority_enum = postgresql.ENUM(LeadPriority, name='leadpriority')
    lead_priority_enum.create(op.get_bind(), checkfirst=True)
    
    contact_method_enum = postgresql.ENUM(ContactMethod, name='contactmethod')
    contact_method_enum.create(op.get_bind(), checkfirst=True)

    # 2. Add columns, passing create_type=False so SQLAlchemy doesn't try to auto-create them
    op.add_column('photographers', sa.Column('lead_source', sa.String(length=100), nullable=True))
    op.add_column('photographers', sa.Column('lead_status', sa.Enum(LeadStatus, name='leadstatus', create_type=False), server_default='NEW', nullable=False))
    op.add_column('photographers', sa.Column('priority', sa.Enum(LeadPriority, name='leadpriority', create_type=False), server_default='MEDIUM', nullable=True))
    op.add_column('photographers', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.add_column('photographers', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photographers', sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photographers', sa.Column('last_contact_method', sa.Enum(ContactMethod, name='contactmethod', create_type=False), nullable=True))
    op.add_column('photographers', sa.Column('last_contact_note', sa.Text(), nullable=True))
    op.add_column('photographers', sa.Column('instagram', sa.String(length=255), nullable=True))
    op.add_column('photographers', sa.Column('facebook', sa.String(length=500), nullable=True))
    op.add_column('photographers', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('photographers', sa.Column('tags', postgresql.ARRAY(sa.String(length=100)), server_default='{}', nullable=False))
    op.add_column('photographers', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('photographers', sa.Column('customer_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop dependent columns first
    op.drop_column('photographers', 'customer_since')
    op.drop_column('photographers', 'internal_notes')
    op.drop_column('photographers', 'tags')
    op.drop_column('photographers', 'website')
    op.drop_column('photographers', 'facebook')
    op.drop_column('photographers', 'instagram')
    op.drop_column('photographers', 'last_contact_note')
    op.drop_column('photographers', 'last_contact_method')
    op.drop_column('photographers', 'next_followup_at')
    op.drop_column('photographers', 'last_contacted_at')
    op.drop_column('photographers', 'assigned_to')
    op.drop_column('photographers', 'priority')
    op.drop_column('photographers', 'lead_status')
    op.drop_column('photographers', 'lead_source')
    # ### end Alembic commands ###
    
    # 2. Drop the PostgreSQL enum types
    lead_status_enum = postgresql.ENUM(LeadStatus, name='leadstatus')
    lead_status_enum.drop(op.get_bind(), checkfirst=True)
    
    lead_priority_enum = postgresql.ENUM(LeadPriority, name='leadpriority')
    lead_priority_enum.drop(op.get_bind(), checkfirst=True)
    
    contact_method_enum = postgresql.ENUM(ContactMethod, name='contactmethod')
    contact_method_enum.drop(op.get_bind(), checkfirst=True)
