"""normalize_order_and_product_catalog

Revision ID: 995f50da59d0
Revises: 838d7cf26cf3
Create Date: 2026-08-02 11:14:56.206127

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995f50da59d0'
down_revision: Union[str, None] = '838d7cf26cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('album_size', sa.String(length=50), nullable=True),
    sa.Column('sheet_type', sa.String(length=100), nullable=True),
    sa.Column('cover_type', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)

    # --- DATA MIGRATION UPGRADE START ---
    connection = op.get_bind()
    orders_data = connection.execute(
        sa.text(
            "SELECT id, album_type, album_size, sheet_type, cover_type, album_quantity, extra_sheet_count, total_amount, created_at "
            "FROM orders"
        )
    ).fetchall()

    product_name_to_id = {}
    for row in orders_data:
        order_id = row[0]
        album_type = row[1] or "Legacy Product"
        album_size = row[2]
        sheet_type = row[3]
        cover_type = row[4]
        album_quantity = row[5] if row[5] is not None and row[5] > 0 else 1
        extra_sheet_count = row[6] or 0
        total_amount = float(row[7]) if row[7] is not None else 0.00
        created_at = row[8]

        unit_price = round(total_amount / album_quantity, 2)

        # Ensure product name is unique
        if album_type not in product_name_to_id:
            # Check if product already exists in products table
            res_prod = connection.execute(
                sa.text("SELECT id FROM products WHERE name = :name"), {"name": album_type}
            ).fetchone()
            if res_prod:
                prod_id = res_prod[0]
            else:
                prod_id = uuid.uuid4()
                connection.execute(
                    sa.text(
                        "INSERT INTO products (id, name, category, size, unit, description, base_price, is_active, created_at, updated_at) "
                        "VALUES (:id, :name, :category, :size, :unit, :description, :base_price, :is_active, :created_at, :updated_at)"
                    ),
                    {
                        "id": prod_id,
                        "name": album_type,
                        "category": "Album",
                        "size": album_size or "Default",
                        "unit": "piece",
                        "description": "Migrated from legacy order system",
                        "base_price": unit_price,
                        "is_active": True,
                        "created_at": created_at,
                        "updated_at": created_at
                    }
                )
            product_name_to_id[album_type] = prod_id
        else:
            prod_id = product_name_to_id[album_type]

        # Insert matching OrderItem
        item_id = uuid.uuid4()
        connection.execute(
            sa.text(
                "INSERT INTO order_items (id, order_id, product_id, product_name, product_category, unit_price, quantity, discount, subtotal, album_size, sheet_type, cover_type, remarks, created_at, updated_at) "
                "VALUES (:id, :order_id, :product_id, :product_name, :product_category, :unit_price, :quantity, :discount, :subtotal, :album_size, :sheet_type, :cover_type, :remarks, :created_at, :updated_at)"
            ),
            {
                "id": item_id,
                "order_id": order_id,
                "product_id": prod_id,
                "product_name": album_type,
                "product_category": "Album",
                "unit_price": unit_price,
                "quantity": album_quantity,
                "discount": 0.00,
                "subtotal": total_amount,
                "album_size": album_size,
                "sheet_type": sheet_type,
                "cover_type": cover_type,
                "remarks": f"Migrated legacy order. Extra sheets: {extra_sheet_count}",
                "created_at": created_at,
                "updated_at": created_at
            }
        )
    # --- DATA MIGRATION UPGRADE END ---

    op.drop_column('orders', 'sheet_type')
    op.drop_column('orders', 'album_type')
    op.drop_column('orders', 'album_quantity')
    op.drop_column('orders', 'extra_sheet_count')
    op.drop_column('orders', 'cover_type')
    op.drop_column('orders', 'album_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('album_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('cover_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('extra_sheet_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('album_quantity', sa.INTEGER(), autoincrement=False, nullable=False, server_default='1'))
    op.add_column('orders', sa.Column('album_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('sheet_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # --- DATA MIGRATION DOWNGRADE START ---
    connection = op.get_bind()
    items_data = connection.execute(
        sa.text(
            "SELECT order_id, product_name, album_size, sheet_type, cover_type, quantity, remarks "
            "FROM order_items"
        )
    ).fetchall()

    for row in items_data:
        order_id = row[0]
        product_name = row[1]
        album_size = row[2]
        sheet_type = row[3]
        cover_type = row[4]
        quantity = row[5]
        remarks = row[6] or ""

        extra_sheet_count = 0
        if "Extra sheets: " in remarks:
            try:
                extra_sheet_count = int(remarks.split("Extra sheets: ")[-1])
            except ValueError:
                pass

        connection.execute(
            sa.text(
                "UPDATE orders "
                "SET album_type = :album_type, album_size = :album_size, sheet_type = :sheet_type, "
                "cover_type = :cover_type, album_quantity = :album_quantity, extra_sheet_count = :extra_sheet_count "
                "WHERE id = :order_id"
            ),
            {
                "album_type": product_name,
                "album_size": album_size,
                "sheet_type": sheet_type,
                "cover_type": cover_type,
                "album_quantity": quantity,
                "extra_sheet_count": extra_sheet_count,
                "order_id": order_id
            }
        )
    # --- DATA MIGRATION DOWNGRADE END ---

    # Remove the server defaults we set for the temporary downgrade compatibility
    op.alter_column('orders', 'extra_sheet_count', server_default=None)
    op.alter_column('orders', 'album_quantity', server_default=None)

    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
