"""add follow up task management

Revision ID: 9dcc5194e0bb
Revises: 21a40470e494
Create Date: 2026-08-04 17:56:18.100525

Creates the `follow_up_tasks` table backing the Follow-up & Task Management module, and
extends the existing `lead_activity_type` enum with the task lifecycle events.

Two hand-written additions to the autogenerated output, both of which Alembic cannot detect
on its own:

1. **The new `lead_activity_type` members.** Alembic's autogenerate does not diff the
   members of an existing Postgres ENUM, so without the explicit ALTER TYPE statements below
   the application would emit TASK_CREATED and friends against a type that does not accept
   them, failing at runtime with `invalid input value for enum`. `ADD VALUE IF NOT EXISTS`
   makes the step idempotent.

2. **Dropping the three new ENUM types on downgrade.** `op.drop_table` removes the table but
   leaves the types behind, so a downgrade followed by a re-upgrade would fail with
   `type "follow_up_type" already exists`.

Note that `ALTER TYPE ... ADD VALUE` cannot run inside a transaction block on PostgreSQL
versions before 12. This project targets a modern Postgres (see docker-compose.yml), where
it is transaction-safe, so the statements run inline with the rest of the migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dcc5194e0bb'
down_revision: Union[str, None] = '21a40470e494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The lead_activity_type members added by this phase. TASK_* cover the task lifecycle;
# MEETING_SCHEDULED is emitted alongside TASK_CREATED when the task is a MEETING.
NEW_ACTIVITY_TYPES = (
    "TASK_CREATED",
    "TASK_COMPLETED",
    "TASK_RESCHEDULED",
    "TASK_CANCELLED",
    "MEETING_SCHEDULED",
)


def upgrade() -> None:
    # Extend the existing activity-type enum before creating anything that writes to it.
    for value in NEW_ACTIVITY_TYPES:
        op.execute(f"ALTER TYPE lead_activity_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('assigned_employee_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('follow_up_type', sa.Enum('CALL', 'WHATSAPP', 'MEETING', 'REMINDER', 'EMAIL', name='follow_up_type'), server_default='CALL', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='follow_up_priority'), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='follow_up_status'), server_default='PENDING', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_tasks_assigned_employee_id'), 'follow_up_tasks', ['assigned_employee_id'], unique=False)
    op.create_index('ix_follow_up_tasks_employee_scheduled', 'follow_up_tasks', ['assigned_employee_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_follow_up_type'), 'follow_up_tasks', ['follow_up_type'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_id'), 'follow_up_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_lead_id'), 'follow_up_tasks', ['lead_id'], unique=False)
    op.create_index('ix_follow_up_tasks_lead_scheduled', 'follow_up_tasks', ['lead_id', sa.text('scheduled_at DESC')], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_priority'), 'follow_up_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_scheduled_at'), 'follow_up_tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_status'), 'follow_up_tasks', ['status'], unique=False)
    op.create_index('ix_follow_up_tasks_status_scheduled', 'follow_up_tasks', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follow_up_tasks_status_scheduled', table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_status'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_scheduled_at'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_priority'), table_name='follow_up_tasks')
    op.drop_index('ix_follow_up_tasks_lead_scheduled', table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_lead_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_follow_up_type'), table_name='follow_up_tasks')
    op.drop_index('ix_follow_up_tasks_employee_scheduled', table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_assigned_employee_id'), table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    # ### end Alembic commands ###

    # Dropping the table leaves its ENUM types behind; without this, a downgrade followed by
    # a re-upgrade fails with `type "follow_up_type" already exists`.
    sa.Enum(name='follow_up_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='follow_up_priority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='follow_up_type').drop(op.get_bind(), checkfirst=True)

    # The added `lead_activity_type` members are deliberately NOT removed. PostgreSQL has no
    # `ALTER TYPE ... DROP VALUE`, so reversing them means recreating the type and rewriting
    # every dependent column — destructive to activity history that this downgrade has no
    # business touching. Leaving the members in place is inert: nothing writes them once the
    # module is gone.
