"""add_audit_log_soft_delete_optimistic_locking_inventory_and_attachments

Revision ID: a8804be68f0c
Revises: 730044ddb4c2
Create Date: 2026-08-02 16:25:35.892939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8804be68f0c'
down_revision: Union[str, None] = '730044ddb4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_name'), 'attachments', ['entity_name'], unique=False)
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', name='auditaction'), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=True)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=True)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', name='inventorytransactiontype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_inventory_item_id'), 'inventory_transactions', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_deliveries_expected_delivery'), 'deliveries', ['expected_delivery'], unique=False)
    op.create_index(op.f('ix_deliveries_tracking_number'), 'deliveries', ['tracking_number'], unique=False)
    op.add_column('order_items', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('order_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_items', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_order_items_production_stage'), 'order_items', ['production_stage'], unique=False)
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_orders_booking_date'), 'orders', ['booking_date'], unique=False)
    op.create_index(op.f('ix_orders_expected_delivery_date'), 'orders', ['expected_delivery_date'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.add_column('photographers', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('photographers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photographers', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'version')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    op.drop_column('photographers', 'version')
    op.drop_column('photographers', 'deleted_at')
    op.drop_column('photographers', 'is_deleted')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_expected_delivery_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_booking_date'), table_name='orders')
    op.drop_column('orders', 'version')
    op.drop_column('orders', 'deleted_at')
    op.drop_column('orders', 'is_deleted')
    op.drop_index(op.f('ix_order_items_production_stage'), table_name='order_items')
    op.drop_column('order_items', 'version')
    op.drop_column('order_items', 'deleted_at')
    op.drop_column('order_items', 'is_deleted')
    op.drop_index(op.f('ix_deliveries_tracking_number'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_expected_delivery'), table_name='deliveries')
    op.drop_index(op.f('ix_inventory_transactions_inventory_item_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_name'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
