"""add_production_workflow

Revision ID: bae259d96ade
Revises: 995f50da59d0
Create Date: 2026-08-02 11:37:29.854076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae259d96ade'
down_revision: Union[str, None] = '995f50da59d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter the orderstatus enum type to support new stages
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'EDITING'")
        op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'COLOR_CORRECTION'")
        op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'QUALITY_CHECK'")
        op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PACKING'")

    # Create productionstage enum type
    production_stage_enum = sa.Enum(
        'RECEIVED', 'DESIGNING', 'EDITING', 'COLOR_CORRECTION', 'PRINTING',
        'LAMINATION', 'QUALITY_CHECK', 'PACKING', 'READY', 'DELIVERED', 'CANCELLED',
        name='productionstage'
    )
    production_stage_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('order_items', sa.Column('production_stage', sa.Enum('RECEIVED', 'DESIGNING', 'EDITING', 'COLOR_CORRECTION', 'PRINTING', 'LAMINATION', 'QUALITY_CHECK', 'PACKING', 'READY', 'DELIVERED', 'CANCELLED', name='productionstage'), server_default='RECEIVED', nullable=False))
    op.add_column('order_items', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_items', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_items', sa.Column('assigned_employee', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('production_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'production_notes')
    op.drop_column('order_items', 'assigned_employee')
    op.drop_column('order_items', 'completed_at')
    op.drop_column('order_items', 'started_at')
    op.drop_column('order_items', 'production_stage')
    
    # Drop productionstage enum type
    production_stage_enum = sa.Enum(
        'RECEIVED', 'DESIGNING', 'EDITING', 'COLOR_CORRECTION', 'PRINTING',
        'LAMINATION', 'QUALITY_CHECK', 'PACKING', 'READY', 'DELIVERED', 'CANCELLED',
        name='productionstage'
    )
    production_stage_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
